name: Release
on:
  push:
    tags:
      - 'v*.*.*'

# Define permissions for GitHub token
permissions:
  contents: write

jobs:
  build-and-release:
    name: Build & Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: windows-x86_64
            os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
            name: todo-tui-windows-amd64.exe
          - build: linux-x86_64
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-musl
            name: todo-tui-linux-amd64
          - build: macos-arm64
            os: macos-latest
            rust: stable
            target: aarch64-apple-darwin
            name: todo-tui-macos-arm64
          - build: macos-x86_64
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
            name: todo-tui-macos-amd64

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install musl-tools (Linux only)
        if: contains(matrix.target, 'musl')
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare Artifact (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          cp target/${{ matrix.target }}/release/tdt ./todo-tui
          mv ./todo-tui ./${{ matrix.name }}
          chmod +x ./${{ matrix.name }}
          shasum -a 256 ./${{ matrix.name }} > ./${{ matrix.name }}.sha256

      - name: Prepare Artifact (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cp target/${{ matrix.target }}/release/tdt.exe ./${{ matrix.name }}
          certutil -hashfile ./${{ matrix.name }} SHA256 | Select-Object -Skip 1 -First 1 | ForEach-Object { "$($_.Trim().ToLower())  ${{ matrix.name }}" } | Set-Content ./${{ matrix.name }}.sha256

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ matrix.name }}
            ${{ matrix.name }}.sha256
